name: ci

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

env:
  BUILD_TYPE: Release
  EM_CACHE_FOLDER: emsdk-cache
  EM_VERSION: 3.1.42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install ghp-import
        run: pip install ghp-import
    
      - id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Configure CMake
        run: emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target pesto -j2

      - name: Prepare
        run: mkdir ${{github.workspace}}/build/pesto/deploy && mv ${{github.workspace}}/build/pesto/pesto.* ${{github.workspace}}/build/pesto/deploy/
      - name: Push
        run: ghp-import -x "$(git rev-parse HEAD)" -p ${{github.workspace}}/build/pesto/deploy/
