name: ci

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

env:
  BUILD_TYPE: Release
  EM_CACHE_FOLDER: emsdk-cache
  EM_VERSION: 3.1.42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Configure CMake
        run: emcmake cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build --target pesto -j2

      - name: Prepare
        run: mkdir $GITHUB_SHA && mv build/pesto/pesto.* $GITHUB_SHA/
      - name: Push
        run: export COMMIT_MSG="$(git log -1 --pretty=%B)" && git fetch && git checkout gh-pages && git add $GITHUB_SHA/ && git config user.email "justin@justindriggers.com" && git config user.name "Justin Driggers" && git commit -m "$COMMIT_MSG" && git push
